services:
  ros:
    container_name: ros2_humble_docker_container
    build: 
      context: .
      args:
        - UID=1000
        - GID=1000
      dockerfile: Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ros_bag:/home/dev-user/humble_ws/ros_bag
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    tty: true
    network_mode: "host"