version: '3'

services:
  ros:
    container_name: ros2_humble_docker_container
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../ros_bag:/home/dev-user/humble_ws/ros_bag
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    tty: true
    network_mode: "host"